import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import type { ReactNode } from "react";
import ConsoleSilencer from "@/components/ConsoleSilencer";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <head>
        <Script id="silence-console-pre" strategy="beforeInteractive">
          {`(function(){try{if('${process.env.NODE_ENV}'==='production'){var n=function(){};var c=window.console||{};['log','error','warn','info','debug'].forEach(function(k){try{c[k]=n}catch(e){}});window.console=c;}}catch(_){}})();`}
        </Script>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ConsoleSilencer />
        {children}
        <ToastContainer position="top-right" autoClose={3000} hideProgressBar={false} newestOnTop closeOnClick pauseOnFocusLoss draggable pauseOnHover theme="dark" />
      </body>
    </html>
  );
}
